// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Volos_Internet_Clock

#include "ui.h"

lv_obj_t * ui_MainScreen;
lv_obj_t * ui_PanelScreenBorder;
lv_obj_t * ui_timeLBL;
lv_obj_t * ui_dateLBL;
lv_obj_t * ui_PanelLine1;
lv_obj_t * ui_fpsLBL;
lv_obj_t * ui_FPS;
lv_obj_t * ui_cornerImage;
lv_obj_t * ui_yearLBL;
lv_obj_t * ui_PanelWeekNumber;
lv_obj_t * ui_weekNumberLBL;
lv_obj_t * ui_PanelWeek;
lv_obj_t * ui_weekLBL;
lv_obj_t * ui_titleLBL;
lv_obj_t * ui_ipLBL;
lv_obj_t * ui_PanelLine2;
lv_obj_t * ui_PanelWiFiQuality;
lv_obj_t * ui_rssiLBL;
lv_obj_t * ui_RSSI;
lv_obj_t * ui_secSyncLBL;
lv_obj_t * ui_ntpSync;
lv_obj_t * ui_Spinner;
lv_obj_t * ui_secLBL;
lv_obj_t * ui_dayPNL;
lv_obj_t * ui_PanelMon;
lv_obj_t * ui_monLBL;
lv_obj_t * ui_PanelTue;
lv_obj_t * ui_tueLBL;
lv_obj_t * ui_PanelWed;
lv_obj_t * ui_wedLBL;
lv_obj_t * ui_PanelThur;
lv_obj_t * ui_Label7;
lv_obj_t * ui_PanelFri;
lv_obj_t * ui_Label11;
lv_obj_t * ui_PanelSat;
lv_obj_t * ui_Label12;
lv_obj_t * ui_PanelSun;
lv_obj_t * ui_Label13;

// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScreenBorder = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelScreenBorder, 324);
    lv_obj_set_height(ui_PanelScreenBorder, 176);
    lv_obj_set_align(ui_PanelScreenBorder, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelScreenBorder, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelScreenBorder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelScreenBorder, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelScreenBorder, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScreenBorder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScreenBorder, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScreenBorder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLBL = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_timeLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeLBL, -165);
    lv_obj_set_y(ui_timeLBL, 7);
    lv_obj_set_align(ui_timeLBL, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_timeLBL, "23:59");
    lv_obj_set_style_text_color(ui_timeLBL, lv_color_hex(0xD2D0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeLBL, &ui_font_MontserratBold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateLBL = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_dateLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateLBL, -164);
    lv_obj_set_y(ui_dateLBL, 55);
    lv_obj_set_align(ui_dateLBL, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_dateLBL, "December 31");
    lv_obj_set_style_text_color(ui_dateLBL, lv_color_hex(0xD2D0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dateLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dateLBL, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLine1 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelLine1, 116);
    lv_obj_set_height(ui_PanelLine1, 5);
    lv_obj_set_x(ui_PanelLine1, -63);
    lv_obj_set_y(ui_PanelLine1, -4);
    lv_obj_set_align(ui_PanelLine1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLine1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelLine1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLine1, lv_color_hex(0x4189CA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLine1, 89, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelLine1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fpsLBL = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_fpsLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fpsLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fpsLBL, -294);
    lv_obj_set_y(ui_fpsLBL, 10);
    lv_obj_set_align(ui_fpsLBL, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_fpsLBL, "FPS:");
    lv_obj_set_style_text_color(ui_fpsLBL, lv_color_hex(0x6B5A6D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fpsLBL, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fpsLBL, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FPS = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_FPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FPS, 6);
    lv_obj_set_y(ui_FPS, 20);
    lv_label_set_text(ui_FPS, "99");
    lv_obj_set_style_text_color(ui_FPS, lv_color_hex(0x6B5A6D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FPS, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FPS, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cornerImage = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_cornerImage, &ui_img_plazmaball_png);
    lv_obj_set_width(ui_cornerImage, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_cornerImage, LV_SIZE_CONTENT);    /// 160
    lv_obj_set_x(ui_cornerImage, -144);
    lv_obj_set_y(ui_cornerImage, 68);
    lv_obj_set_align(ui_cornerImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cornerImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cornerImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yearLBL = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_yearLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_yearLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_yearLBL, -36);
    lv_obj_set_y(ui_yearLBL, 13);
    lv_obj_set_align(ui_yearLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_yearLBL, "2025");
    lv_obj_set_style_text_color(ui_yearLBL, lv_color_hex(0xD2D0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_yearLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_yearLBL, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWeekNumber = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelWeekNumber, 60);
    lv_obj_set_height(ui_PanelWeekNumber, 32);
    lv_obj_set_x(ui_PanelWeekNumber, -36);
    lv_obj_set_y(ui_PanelWeekNumber, 45);
    lv_obj_set_align(ui_PanelWeekNumber, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWeekNumber, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelWeekNumber, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelWeekNumber, lv_color_hex(0x96AA10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWeekNumber, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelWeekNumber, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weekNumberLBL = lv_label_create(ui_PanelWeekNumber);
    lv_obj_set_width(ui_weekNumberLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weekNumberLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_weekNumberLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weekNumberLBL, "Cal.\nWeek");
    lv_obj_set_style_text_letter_space(ui_weekNumberLBL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_weekNumberLBL, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_weekNumberLBL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWeek = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelWeek, 60);
    lv_obj_set_height(ui_PanelWeek, 18);
    lv_obj_set_x(ui_PanelWeek, -36);
    lv_obj_set_y(ui_PanelWeek, 74);
    lv_obj_set_align(ui_PanelWeek, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWeek, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelWeek, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelWeek, lv_color_hex(0x96AA10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWeek, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelWeek, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weekLBL = lv_label_create(ui_PanelWeek);
    lv_obj_set_width(ui_weekLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weekLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_weekLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weekLBL, "52");
    lv_obj_set_style_text_font(ui_weekLBL, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_titleLBL = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_titleLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titleLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_titleLBL, 164);
    lv_obj_set_y(ui_titleLBL, 10);
    lv_label_set_text(ui_titleLBL, "INTERNET CLOCK");
    lv_obj_set_style_text_color(ui_titleLBL, lv_color_hex(0xCD25D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_titleLBL, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_titleLBL, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ipLBL = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ipLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ipLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ipLBL, 164);
    lv_obj_set_y(ui_ipLBL, 25);
    lv_label_set_text(ui_ipLBL, "192.168.254.254");
    lv_obj_set_style_text_color(ui_ipLBL, lv_color_hex(0x67B2C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ipLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLine2 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelLine2, 110);
    lv_obj_set_height(ui_PanelLine2, 5);
    lv_obj_set_x(ui_PanelLine2, 60);
    lv_obj_set_y(ui_PanelLine2, -42);
    lv_obj_set_align(ui_PanelLine2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLine2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelLine2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLine2, lv_color_hex(0x4189CA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLine2, 89, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelLine2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWiFiQuality = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelWiFiQuality, 7);
    lv_obj_set_height(ui_PanelWiFiQuality, 7);
    lv_obj_set_x(ui_PanelWiFiQuality, 65);
    lv_obj_set_y(ui_PanelWiFiQuality, -21);
    lv_obj_set_align(ui_PanelWiFiQuality, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWiFiQuality, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelWiFiQuality, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelWiFiQuality, lv_color_hex(0x41C241), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWiFiQuality, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelWiFiQuality, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rssiLBL = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_rssiLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rssiLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rssiLBL, -103);
    lv_obj_set_y(ui_rssiLBL, 60);
    lv_obj_set_align(ui_rssiLBL, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_rssiLBL, "RSSI :");
    lv_obj_set_style_text_color(ui_rssiLBL, lv_color_hex(0x6B5A6D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rssiLBL, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rssiLBL, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RSSI = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RSSI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RSSI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RSSI, -46);
    lv_obj_set_y(ui_RSSI, 60);
    lv_obj_set_align(ui_RSSI, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_RSSI, "-99dbm");
    lv_obj_set_style_text_color(ui_RSSI, lv_color_hex(0x6B5A6D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RSSI, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RSSI, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secSyncLBL = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_secSyncLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secSyncLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secSyncLBL, -82);
    lv_obj_set_y(ui_secSyncLBL, 49);
    lv_obj_set_align(ui_secSyncLBL, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_secSyncLBL, "NTP Sync :");
    lv_obj_set_style_text_color(ui_secSyncLBL, lv_color_hex(0x6B5A6D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secSyncLBL, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secSyncLBL, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ntpSync = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ntpSync, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ntpSync, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ntpSync, -47);
    lv_obj_set_y(ui_ntpSync, 49);
    lv_obj_set_align(ui_ntpSync, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_ntpSync, "7200s");
    lv_obj_set_style_text_color(ui_ntpSync, lv_color_hex(0x6B5A6D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ntpSync, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ntpSync, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner = lv_spinner_create(ui_MainScreen, 1000, 90);
    lv_obj_set_width(ui_Spinner, 90);
    lv_obj_set_height(ui_Spinner, 90);
    lv_obj_set_x(ui_Spinner, 61);
    lv_obj_set_y(ui_Spinner, 35);
    lv_obj_set_align(ui_Spinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_Spinner, &ui_img_85012636, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_secLBL = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_secLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secLBL, 61);
    lv_obj_set_y(ui_secLBL, 35);
    lv_obj_set_align(ui_secLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_secLBL, "59");
    lv_obj_set_style_text_color(ui_secLBL, lv_color_hex(0x14B1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secLBL, &ui_font_MontserratBold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dayPNL = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_dayPNL, 6);
    lv_obj_set_height(ui_dayPNL, 18);
    lv_obj_set_x(ui_dayPNL, 122);
    lv_obj_set_y(ui_dayPNL, -69);
    lv_obj_set_align(ui_dayPNL, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dayPNL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dayPNL, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dayPNL, lv_color_hex(0x96AA10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dayPNL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dayPNL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMon = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelMon, 23);
    lv_obj_set_height(ui_PanelMon, 18);
    lv_obj_set_x(ui_PanelMon, 138);
    lv_obj_set_y(ui_PanelMon, -69);
    lv_obj_set_align(ui_PanelMon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelMon, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelMon, lv_color_hex(0x0C4C72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelMon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_monLBL = lv_label_create(ui_PanelMon);
    lv_obj_set_width(ui_monLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_monLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_monLBL, -1);
    lv_obj_set_y(ui_monLBL, 0);
    lv_obj_set_align(ui_monLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_monLBL, "MO");
    lv_obj_set_style_text_font(ui_monLBL, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTue = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelTue, 23);
    lv_obj_set_height(ui_PanelTue, 18);
    lv_obj_set_x(ui_PanelTue, 138);
    lv_obj_set_y(ui_PanelTue, -46);
    lv_obj_set_align(ui_PanelTue, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTue, lv_color_hex(0x0C4C72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tueLBL = lv_label_create(ui_PanelTue);
    lv_obj_set_width(ui_tueLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tueLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tueLBL, -1);
    lv_obj_set_y(ui_tueLBL, 0);
    lv_obj_set_align(ui_tueLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tueLBL, "TU");
    lv_obj_set_style_text_font(ui_tueLBL, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWed = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelWed, 23);
    lv_obj_set_height(ui_PanelWed, 18);
    lv_obj_set_x(ui_PanelWed, 138);
    lv_obj_set_y(ui_PanelWed, -23);
    lv_obj_set_align(ui_PanelWed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelWed, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelWed, lv_color_hex(0x0C4C72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelWed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wedLBL = lv_label_create(ui_PanelWed);
    lv_obj_set_width(ui_wedLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wedLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wedLBL, -1);
    lv_obj_set_y(ui_wedLBL, 0);
    lv_obj_set_align(ui_wedLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wedLBL, "WE");
    lv_obj_set_style_text_font(ui_wedLBL, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelThur = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelThur, 23);
    lv_obj_set_height(ui_PanelThur, 18);
    lv_obj_set_x(ui_PanelThur, 138);
    lv_obj_set_y(ui_PanelThur, 0);
    lv_obj_set_align(ui_PanelThur, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelThur, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelThur, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelThur, lv_color_hex(0x0C4C72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelThur, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelThur, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_PanelThur);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -1);
    lv_obj_set_y(ui_Label7, 0);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "TH");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelFri = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelFri, 23);
    lv_obj_set_height(ui_PanelFri, 18);
    lv_obj_set_x(ui_PanelFri, 138);
    lv_obj_set_y(ui_PanelFri, 23);
    lv_obj_set_align(ui_PanelFri, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelFri, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelFri, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelFri, lv_color_hex(0x0C4C72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelFri, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelFri, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_PanelFri);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -1);
    lv_obj_set_y(ui_Label11, 0);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "FR");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSat = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelSat, 23);
    lv_obj_set_height(ui_PanelSat, 18);
    lv_obj_set_x(ui_PanelSat, 138);
    lv_obj_set_y(ui_PanelSat, 46);
    lv_obj_set_align(ui_PanelSat, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSat, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSat, lv_color_hex(0x9A11A2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_PanelSat);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -1);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "SA");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSun = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelSun, 23);
    lv_obj_set_height(ui_PanelSun, 18);
    lv_obj_set_x(ui_PanelSun, 138);
    lv_obj_set_y(ui_PanelSun, 69);
    lv_obj_set_align(ui_PanelSun, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSun, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSun, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSun, lv_color_hex(0x9A11A2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSun, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSun, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_PanelSun);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -1);
    lv_obj_set_y(ui_Label13, 0);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "SU");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_PanelScreenBorder = NULL;
    ui_timeLBL = NULL;
    ui_dateLBL = NULL;
    ui_PanelLine1 = NULL;
    ui_fpsLBL = NULL;
    ui_FPS = NULL;
    ui_cornerImage = NULL;
    ui_yearLBL = NULL;
    ui_PanelWeekNumber = NULL;
    ui_weekNumberLBL = NULL;
    ui_PanelWeek = NULL;
    ui_weekLBL = NULL;
    ui_titleLBL = NULL;
    ui_ipLBL = NULL;
    ui_PanelLine2 = NULL;
    ui_PanelWiFiQuality = NULL;
    ui_rssiLBL = NULL;
    ui_RSSI = NULL;
    ui_secSyncLBL = NULL;
    ui_ntpSync = NULL;
    ui_Spinner = NULL;
    ui_secLBL = NULL;
    ui_dayPNL = NULL;
    ui_PanelMon = NULL;
    ui_monLBL = NULL;
    ui_PanelTue = NULL;
    ui_tueLBL = NULL;
    ui_PanelWed = NULL;
    ui_wedLBL = NULL;
    ui_PanelThur = NULL;
    ui_Label7 = NULL;
    ui_PanelFri = NULL;
    ui_Label11 = NULL;
    ui_PanelSat = NULL;
    ui_Label12 = NULL;
    ui_PanelSun = NULL;
    ui_Label13 = NULL;

}
