// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Volos_Internet_Clock

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_PanelScreenBorder;
extern lv_obj_t * ui_timeLBL;
extern lv_obj_t * ui_dateLBL;
extern lv_obj_t * ui_PanelLine1;
extern lv_obj_t * ui_fpsLBL;
extern lv_obj_t * ui_FPS;
extern lv_obj_t * ui_cornerImage;
extern lv_obj_t * ui_yearLBL;
extern lv_obj_t * ui_PanelWeekNumber;
extern lv_obj_t * ui_weekNumberLBL;
extern lv_obj_t * ui_PanelWeek;
extern lv_obj_t * ui_weekLBL;
extern lv_obj_t * ui_titleLBL;
extern lv_obj_t * ui_ipLBL;
extern lv_obj_t * ui_PanelLine2;
extern lv_obj_t * ui_PanelWiFiQuality;
extern lv_obj_t * ui_rssiLBL;
extern lv_obj_t * ui_RSSI;
extern lv_obj_t * ui_secSyncLBL;
extern lv_obj_t * ui_ntpSync;
extern lv_obj_t * ui_Spinner;
extern lv_obj_t * ui_secLBL;
extern lv_obj_t * ui_dayPNL;
extern lv_obj_t * ui_PanelMon;
extern lv_obj_t * ui_monLBL;
extern lv_obj_t * ui_PanelTue;
extern lv_obj_t * ui_tueLBL;
extern lv_obj_t * ui_PanelWed;
extern lv_obj_t * ui_wedLBL;
extern lv_obj_t * ui_PanelThur;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_PanelFri;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_PanelSat;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_PanelSun;
extern lv_obj_t * ui_Label13;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

